/**
 * Clase FrmRegistrarTraslado.java creada el 13/05/2023.
 */
package org.itson.capaaplicacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;
import javax.swing.plaf.basic.BasicOptionPaneUI;

/**
 * 
 * @author Equipo 3 
 * Luis Pablo Ayón Figueroa
 * Mario Díaz Padilla
 * Gabriel Alberto Mancinas Cota
 * Ángel de Jesús Valenzuela García
 */
public class FrmRegistrarTraslado extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FrmRegistrarTraslado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private void regresarMenu(){
        FrmMenu frm = new FrmMenu();
        frm.setVisible(true);
        this.setVisible(false);
    }
    
    public void mostrarMensaje(String mensaje, String titulo) {
    UIManager.put("OptionPane.background", new ColorUIResource(20,174,92));
    UIManager.put("Panel.background", new ColorUIResource(20,174,92));
    UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Myanmar Text", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.PLAIN_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplFondoGeneral = new javax.swing.JPanel();
        jplFondoSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jplFondo1 = new javax.swing.JPanel();
        lblResiduoTrasladar = new javax.swing.JLabel();
        lblCantidadTrasladar = new javax.swing.JLabel();
        cbxResiduos = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        lblUnidadDeMedida = new javax.swing.JLabel();
        cbxUnidad = new javax.swing.JComboBox<>();
        btnSolicitar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jplFondo2 = new javax.swing.JPanel();
        lblFechaTraslado = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        lblDestino = new javax.swing.JLabel();
        cbxDestinos = new javax.swing.JComboBox<>();
        lblPresupuesto = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        lblInformacionSolicitud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setResizable(false);

        jplFondoGeneral.setBackground(new java.awt.Color(232, 233, 217));
        jplFondoGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplFondoSuperior.setBackground(new java.awt.Color(4, 80, 40));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar traslado");

        javax.swing.GroupLayout jplFondoSuperiorLayout = new javax.swing.GroupLayout(jplFondoSuperior);
        jplFondoSuperior.setLayout(jplFondoSuperiorLayout);
        jplFondoSuperiorLayout.setHorizontalGroup(
            jplFondoSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplFondoSuperiorLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
        );
        jplFondoSuperiorLayout.setVerticalGroup(
            jplFondoSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplFondoSuperiorLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jplFondoGeneral.add(jplFondoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 70));

        jplFondo1.setBackground(new java.awt.Color(20, 174, 92));

        lblResiduoTrasladar.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblResiduoTrasladar.setForeground(new java.awt.Color(255, 255, 255));
        lblResiduoTrasladar.setText("Residuo a trasladar");

        lblCantidadTrasladar.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblCantidadTrasladar.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadTrasladar.setText("Cantidad a trasladar");

        cbxResiduos.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        cbxResiduos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCantidad.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        lblUnidadDeMedida.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblUnidadDeMedida.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidadDeMedida.setText("Unidad de medida");

        cbxUnidad.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        cbxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramos", "Litros" }));

        javax.swing.GroupLayout jplFondo1Layout = new javax.swing.GroupLayout(jplFondo1);
        jplFondo1.setLayout(jplFondo1Layout);
        jplFondo1Layout.setHorizontalGroup(
            jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCantidadTrasladar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResiduoTrasladar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblUnidadDeMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxUnidad, 0, 211, Short.MAX_VALUE)
                    .addComponent(cbxResiduos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidad))
                .addContainerGap())
        );
        jplFondo1Layout.setVerticalGroup(
            jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResiduoTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadDeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jplFondoGeneral.add(jplFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, 110));

        btnSolicitar.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        btnSolicitar.setText("Solicitar");
        btnSolicitar.setBorder(null);
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        jplFondoGeneral.add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 70, 30));

        btnVolver.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jplFondoGeneral.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 30));

        jplFondo2.setBackground(new java.awt.Color(175, 244, 198));

        lblFechaTraslado.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblFechaTraslado.setText("Fecha del traslado");

        lblDestino.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblDestino.setText("Destino");

        cbxDestinos.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        cbxDestinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramos", "Litros" }));

        lblPresupuesto.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblPresupuesto.setText("Presupuesto base");

        txtPresupuesto.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        javax.swing.GroupLayout jplFondo2Layout = new javax.swing.GroupLayout(jplFondo2);
        jplFondo2.setLayout(jplFondo2Layout);
        jplFondo2Layout.setHorizontalGroup(
            jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaTraslado)
                    .addComponent(lblDestino)
                    .addComponent(lblPresupuesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxDestinos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtPresupuesto))
                .addContainerGap())
        );
        jplFondo2Layout.setVerticalGroup(
            jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jplFondoGeneral.add(jplFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 420, 120));

        lblInformacionSolicitud.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblInformacionSolicitud.setText("Información de solicitud");
        jplFondoGeneral.add(lblInformacionSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplFondoGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplFondoGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
       //mostrarMensaje("Registro realizado.","Éxito");
       mostrarMensaje("Registro éxitoso","éxito");
       regresarMenu();
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        regresarMenu();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDestinos;
    private javax.swing.JComboBox<String> cbxResiduos;
    private javax.swing.JComboBox<String> cbxUnidad;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jplFondo1;
    private javax.swing.JPanel jplFondo2;
    private javax.swing.JPanel jplFondoGeneral;
    private javax.swing.JPanel jplFondoSuperior;
    private javax.swing.JLabel lblCantidadTrasladar;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFechaTraslado;
    private javax.swing.JLabel lblInformacionSolicitud;
    private javax.swing.JLabel lblPresupuesto;
    private javax.swing.JLabel lblResiduoTrasladar;
    private javax.swing.JLabel lblUnidadDeMedida;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
